name: STM32L4_L4+

on:
  push:
    branches: [ master ]
    paths:
      - 'core/**'
      - 'cmake/**'
      - 'STMicroelectronics/STM32L4_L4\+/**'
  pull_request:
    branches: [ master ]
    paths:
      - 'core/**'
      - 'cmake/**'
      - 'STMicroelectronics/STM32L4_L4\+/**'

defaults:
  run:
    working-directory: STMicroelectronics/STM32L4_L4+

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          submodules: recursive

      # Get the ARM GCC compiler
      - name: Install tools for linux
        if: matrix.os == 'ubuntu-latest'
        run: sudo apt install gcc-arm-none-eabi cmake

      - name: Install Ninja
        uses: seanmiddleditch/gha-setup-ninja@v1

      - name: Build project
        run: |
          cmake -Bbuild -GNinja -DCMAKE_TOOLCHAIN_FILE="../../cmake/arm-gcc-cortex-m4.cmake" 
          cmake --build build
